# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4db6246a0df783ead06d616dba78cfb4f61a89677417e3d9ac5a01bb1cfb86aa3bc0eb97baf50d4a529e4f10b38f51fefea893ca8a2f2301ff44bfdde35958d8

test:
  secret_key_base: 12999eefeb6debad51169d5164926a13580381b5c32f0c99cb5fc27b85bd81d45ba97e8d0d8944dbb4a6a35c7ae8299cf68c4c5e24badeebac11134178c92ee3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base:  4db6246a0df783ead06d616dba78cfb4f61a89677417e3d9ac5a01bb1cfb86aa3bc0eb97baf50d4a529e4f10b38f51fefea893ca8a2f2301ff44bfdde35958d8
