json.id   service.id
json.title   service.title
json.photo   service.photo_url
json.description   service.description
json.email    service.email
json.phone_number    service.phone_number
json.school   service.school
json.created_at   service.created_at
json.updated_at   service.updated_at
json.link    service.link
json.Document_Link    service.Document_Link
json.Notes   service.Notes